// In-memory data store for development (without MongoDB)
// This will be replaced by actual database when MongoDB is set up

const users = [
  {
    _id: '1',
    name: 'Admin User',
    email: 'admin@thakurshop.com',
    password: '$2a$10$ZJ8q8K7h8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K', // admin123 hashed
    isAdmin: true,
    phone: '+91 7644997168',
    address: { city: 'Ranchi', state: 'Jharkhand', country: 'India' },
    createdAt: new Date(),
  },
  {
    _id: '2',
    name: 'John Doe',
    email: 'john@example.com',
    password: '$2a$10$ZJ8q8K7h8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K', // password123 hashed
    isAdmin: false,
    phone: '+91 9876543210',
    address: { city: 'Mumbai', state: 'Maharashtra', country: 'India' },
    createdAt: new Date(),
  },
];

const products = [
  {
    _id: '1',
    name: 'MacBook Pro 16',
    description: 'The most powerful MacBook Pro ever with M2 chip, stunning Retina display, and incredible battery life.',
    price: 2499,
    category: 'Electronics',
    images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80'],
    brand: 'Apple',
    stock: 25,
    rating: 4.8,
    reviewsNumber: 342,
    sales: 156,
    reviews: [],
    createdAt: new Date(),
  },
  {
    _id: '2',
    name: 'iPhone 15 Pro',
    description: 'Latest iPhone with titanium design, A17 Pro chip, and pro camera system. The most advanced iPhone yet.',
    price: 999,
    category: 'Electronics',
    images: ['https://images.unsplash.com/photo-1592286927505-1def25115558?w=800&q=80'],
    brand: 'Apple',
    stock: 50,
    rating: 4.9,
    reviewsNumber: 521,
    sales: 324,
    reviews: [],
    createdAt: new Date(),
  },
  {
    _id: '3',
    name: 'The Great Gatsby',
    description: "F. Scott Fitzgerald's classic American novel set in the Jazz Age. A timeless story of love, wealth, and the American Dream.",
    price: 12.99,
    category: 'Books',
    images: ['https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&q=80'],
    brand: 'Scribner',
    stock: 200,
    rating: 4.6,
    reviewsNumber: 1205,
    sales: 892,
    reviews: [],
    createdAt: new Date(),
  },
  {
    _id: '4',
    name: 'Premium Cotton Casual Shirt',
    description: 'Premium 100% cotton casual shirt perfect for any occasion. Comfortable, breathable, and stylish.',
    price: 39.99,
    category: 'Fashion',
    images: ['https://images.unsplash.com/photo-1598644902792-4db5ea6b5c44?w=800&q=80'],
    brand: 'FashionCo',
    stock: 75,
    rating: 4.3,
    reviewsNumber: 89,
    sales: 234,
    reviews: [],
    createdAt: new Date(),
  },
  {
    _id: '5',
    name: 'Programmable Coffee Maker',
    description: 'Programmable coffee maker with thermal carafe. Brew your perfect cup every time with customizable settings.',
    price: 79.99,
    category: 'Home & Kitchen',
    images: ['https://images.unsplash.com/photo-1517668808822-9ebb02ae2a0e?w=800&q=80'],
    brand: 'BrewMaster',
    stock: 40,
    rating: 4.4,
    reviewsNumber: 234,
    sales: 178,
    reviews: [],
    createdAt: new Date(),
  },
  {
    _id: '6',
    name: 'Premium Yoga Mat',
    description: 'Non-slip yoga mat with extra cushioning for ultimate comfort. Perfect for all yoga styles and exercises.',
    price: 29.99,
    category: 'Sports',
    images: ['https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&q=80'],
    brand: 'FitPro',
    stock: 100,
    rating: 4.7,
    reviewsNumber: 156,
    sales: 423,
    reviews: [],
    createdAt: new Date(),
  },
  {
    _id: '7',
    name: 'LEGO City Construction Set',
    description: 'Build your own city with this amazing LEGO set featuring hundreds of colorful bricks. Endless creative possibilities.',
    price: 89.99,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1594787318286-3d835c1cab83?w=800&q=80'],
    brand: 'LEGO',
    stock: 60,
    rating: 4.9,
    reviewsNumber: 412,
    sales: 289,
    reviews: [],
    createdAt: new Date(),
  },
  {
    _id: '8',
    name: 'Premium Wireless Headphones',
    description: 'Premium noise-cancelling headphones with crystal-clear sound. Active noise cancellation, 30-hour battery life.',
    price: 199.99,
    category: 'Electronics',
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80'],
    brand: 'SoundMax',
    stock: 45,
    rating: 4.6,
    reviewsNumber: 678,
    sales: 567,
    reviews: [],
    createdAt: new Date(),
  },
  {
    _id: '9',
    name: '4K Action Camera',
    description: 'Rugged 4K action camera with image stabilization and waterproof casing for outdoor adventures.',
    price: 249.99,
    category: 'Electronics',
    images: ['https://images.unsplash.com/photo-1508898578281-774ac4893c0c?w=800&q=80'],
    brand: 'GoProMax',
    stock: 70,
    rating: 4.5,
    reviewsNumber: 342,
    sales: 198,
    reviews: [],
    createdAt: new Date(),
  },
  {
    _id: '10',
    name: 'Stainless Steel Air Fryer',
    description: 'Family-size air fryer with digital controls and rapid air circulation for crispy, healthy meals.',
    price: 129.99,
    category: 'Home & Kitchen',
    images: ['https://images.unsplash.com/photo-1612874472278-5c1b09f0e5f6?w=800&q=80'],
    brand: 'CrispyChef',
    stock: 90,
    rating: 4.4,
    reviewsNumber: 265,
    sales: 312,
    reviews: [],
    createdAt: new Date(),
  },
  {
    _id: '11',
    name: 'Running Shoes Pro',
    description: 'Lightweight, breathable running shoes with responsive cushioning for daily training.',
    price: 89.99,
    category: 'Sports',
    images: ['https://images.unsplash.com/photo-1528701800489-20be9c1f4ab4?w=800&q=80'],
    brand: 'StrideX',
    stock: 120,
    rating: 4.2,
    reviewsNumber: 198,
    sales: 421,
    reviews: [],
    createdAt: new Date(),
  },
  {
    _id: '12',
    name: 'Bluetooth Party Speaker',
    description: 'Portable Bluetooth speaker with deep bass, LED lights, and 18-hour battery life.',
    price: 149.99,
    category: 'Electronics',
    images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80'],
    brand: 'SoundWave',
    stock: 65,
    rating: 4.5,
    reviewsNumber: 254,
    sales: 367,
    reviews: [],
    createdAt: new Date(),
  },
];

const orders = [];
const carts = {};

module.exports = {
  users,
  products,
  orders,
  carts,
};
